services:
  postgres:
    container_name: postgres
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_db
    networks:
      - movie


networks:
  movie:
    driver: bridge
